In [1]:
%pip install numpy

In [ ]:
import numpy as np 

In [ ]:
PT = "mohamedr"
PT

'mohamedr'

In [ ]:
PT = PT.replace(" ", "")
PT #to remove spaces

'mohamedr'

In [ ]:
PT = PT.lower()
PT # to set all letters to lower case

'mohamedr'

In [ ]:
key = "test"
key # the key

'test'

In [ ]:
EAM = {chr(i):i-97 for i in range(97, 97+26)}
print(EAM) # change letters into numbers with map

{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 'w': 22, 'x': 23, 'y': 24, 'z': 25}


In [ ]:
EAM_rev = {i-97:chr(i) for i in range(97, 97+26)}
print(EAM_rev)# to return numbers into letters

{0: 'a', 1: 'b', 2: 'c', 3: 'd', 4: 'e', 5: 'f', 6: 'g', 7: 'h', 8: 'i', 9: 'j', 10: 'k', 11: 'l', 12: 'm', 13: 'n', 14: 'o', 15: 'p', 16: 'q', 17: 'r', 18: 's', 19: 't', 20: 'u', 21: 'v', 22: 'w', 23: 'x', 24: 'y', 25: 'z'}


In [ ]:
PT_numbers = [EAM[i] for i in PT]
PT_numbers # change the plain text letters into numbers

[12, 14, 7, 0, 12, 4, 3, 17]

In [ ]:
key_numbers = [EAM[i] for i in key]
key_numbers # change the key letters into numbers

[19, 4, 18, 19]

In [ ]:
BL = len(key_numbers)//2 # Block Length
BL # setting block length to use in making matrices

2

In [ ]:
key_matrix = np.array(key_numbers).reshape(BL, BL)
print(key_matrix) # setting up key matrix

[[19  4]
 [18 19]]


In [ ]:
PT_array = np.array(PT_numbers)
print(PT_array) # converting text converted numbers into array to make a matrix

[12 14  7  0 12  4  3 17]


In [ ]:
PT_blocks = np.split(PT_array, len(PT_array)/BL)
print(PT_blocks) #making blocks to multiply by the key matrix

[array([12, 14]), array([7, 0]), array([12,  4]), array([ 3, 17])]


In [ ]:
CT_blocks = [np.matmul(PT_blocks[i], key_matrix) % 26 for i in range(len(PT)//BL)]
CT_blocks # enycrypted blocks

[array([12,  2], dtype=int32),
 array([3, 2], dtype=int32),
 array([14, 20], dtype=int32),
 array([25, 23], dtype=int32)]

In [ ]:
CT_array = np.concatenate(CT_blocks)
CT_array #convert encrypted blocks into array

array([12,  2,  3,  2, 14, 20, 25, 23], dtype=int32)

In [ ]:
CT = [EAM_rev[CT_array[i]] for i in range(len(CT_array))]
CT #convert encrypted text numbers into list of letters

['m', 'c', 'd', 'c', 'o', 'u', 'z', 'x']

In [ ]:
''.join(CT)# to join enycrpted letters

'mcdcouzx'

# getting inverse

In [ ]:
CT_numbers = [EAM[i] for i in CT]
CT_numbers # convert encrypted letters into numbers again

[12, 2, 3, 2, 14, 20, 25, 23]

In [ ]:
adj_key_matrix = np.linalg.inv(key_matrix) * round(np.linalg.det(key_matrix)) # important distinction between int and round
adj_key_matrix# getting matrix adjective

array([[ 19.,  -4.],
       [-18.,  19.]])

In [ ]:
round(np.linalg.det(key_matrix))#matrix det

289

In [ ]:
pow(round(np.linalg.det(key_matrix)), -1, 26)#det inverse

9

In [ ]:
key_inverse = (pow(round(np.linalg.det(key_matrix)), -1, 26) * adj_key_matrix) % 26

key_inverse # getting key inverse


array([[15., 16.],
       [20., 15.]])

# Decryption

In [ ]:
CT_array = np.array(CT_numbers)
CT_array # converting enycrypted numbers into array

array([12,  2,  3,  2, 14, 20, 25, 23])

In [ ]:
CT_blocks = np.split(CT_array, len(CT_numbers)//BL)
CT_blocks #convert into blocks to multi by inverse of key

[array([12,  2]), array([3, 2]), array([14, 20]), array([25, 23])]

In [ ]:
CT_blocks = np.split(CT_array, len(CT_numbers)//BL)
CT_blocks

[array([12,  2]), array([3, 2]), array([14, 20]), array([25, 23])]

In [ ]:
PT_blocks = [np.matmul(CT_blocks[i], key_inverse) % 26 for i in range(len(PT)//BL)]
PT_blocks# multible by key invers to restor original values

[array([12., 14.]),
 array([7.00000000e+00, 2.84217094e-14]),
 array([12.,  4.]),
 array([ 3., 17.])]

In [ ]:
PT_array = np.concatenate(PT_blocks)
PT_array# retore values into array

array([1.20000000e+01, 1.40000000e+01, 7.00000000e+00, 2.84217094e-14,
       1.20000000e+01, 4.00000000e+00, 3.00000000e+00, 1.70000000e+01])

In [ ]:
[EAM_rev[round(i)] for i in PT_array] #convert to letters and the text is restord

['m', 'o', 'h', 'a', 'm', 'e', 'd', 'r']